version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: statreg_db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "test_user", "-d", "statreg_db"]
      interval: 2s
      timeout: 2s
      retries: 30

  app:
    image: node:24
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run build && npm run generate && npm run db:deploy && npm run seed && npm run start"
    expose:
      - '8080'
    environment:
      NODE_ENV: test
      PGURL: postgresql://test_user:test_pass@db:5432/statreg_db?sslmode=disable
      AUTH_ENABLED: false 
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/docs"] # TODO proper health check here 
      interval: 2s
      timeout: 2s
      retries: 30
      
  tests:
    image: node:24
    working_dir: /app
    volumes:
      - .:/app
    environment:
      NODE_ENV: test
      API_URL: http://app:8080
    depends_on:
      app:
        condition: service_healthy
    command: sh -c "npm run test:integration"