version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: statreg-db
    environment:
      POSTGRES_USER: cob
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: statreg-db
    ports:
      - "5432:5432"
    volumes:
      - ./src/schema/statreg.sql:/docker-entrypoint-initdb.d/statreg.sql:ro