apiVersion: data.nais.io/v1
kind: Postgres
metadata:
  name: statreg-api-db
spec:
  cluster:
    audit:
      enabled: true
    majorVersion: "18"
    resources:
      cpu: 200m
      diskSize: 2Gi
      memory: 2Gi
  database:
    collation: nb_NO
