apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: ssbno-developers
  name: ssbno-statreg-api
  namespace: ssbno

spec:
  ingresses:
  - https://ssbno-statreg-api.intern.test.ssb.no 
  image: '{{ image }}' # Injected from the GitHub Action
  port: 8080

  envFrom:
  - secret: login-config-ssbno-statreg-api

  env:
    - name: KLASS_BASE_URL
      value: https://data.qa.ssb.no

  accessPolicy:
    outbound:
      external:
      - host: auth.test.ssb.no

  login:
    provider: openid
    enforce:
      enabled: true
      excludePaths:
        - /secret
        - /api-docs
  
  gcp:
      sqlInstances:
        - type: POSTGRES_17
          # See Nais docs: https://docs.ssb.cloud.nais.io/workloads/application/reference/application-spec/#gcpsqlinstancestier
          tier: db-f1-micro # This tier MUST be increased for PROD! No SLA unless custom!
          diskAutoresize: true
          diskAutoresizeLimit: 50
          flags:
            - name: "cloudsql.enable_pgaudit"
              value: "on"
            - name: "pgaudit.log"
              value: "write"
            - name: "pgaudit.log_parameter"
              value: "on"          
          databases:
            - name: statreg-db

  prometheus:
    enabled: true
    path: /metrics
    port: "9000"
  
  liveness:
    path: /live
    port: 9000
    failureThreshold: 3
    initialDelay: 10
    periodSeconds: 30
    timeout: 5
  
  readiness:
    path: /ready
    port: 9000
    failureThreshold: 1
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  
  startup:
    path: /live
    port: 9000
    failureThreshold: 3
    initialDelay: 10
    periodSeconds: 30
    timeout: 5
status: {}
