apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: ssbno-developers
  name: ssbno-statreg-api
  namespace: ssbno
spec:
  image: '{{ image }}' # Injected from the GitHub Action
  ingresses:
  - https://ssbno-statreg-api.intern.test.ssb.no
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
    port: "9000"
  liveness:
    path: /live 
    port: 9000
  readiness:
    path: /ready
    port: 9000
status: {}