apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  annotations:
    nais.io/read-only-file-system: "false" # Need to try this, in order to generate client identity on runtime
  labels:
    team: ssbno-developers
  name: ssbno-statreg-api
  namespace: ssbno

spec:
  ingresses:
  - https://ssbno-statreg-api.intern.test.ssb.no 
  image: '{{ image }}' # Injected from the GitHub Action
  port: 8080

  envFrom:
  - secret: login-config-ssbno-statreg-api
  - secret: statreg-api-secrets

  env:
    - name: AUTH_ENABLED
      value: "true"
    - name: KLASS_BASE_URL
      value: https://data.qa.ssb.no
    - name: KEYCLOAK_REALM_ISSUER
      value: https://auth.test.ssb.no/realms/ssb
    - name: KEYCLOAK_JWKS_URI
      value: https://auth.test.ssb.no/realms/ssb/protocol/openid-connect/certs
    - name: KEYCLOAK_TOKEN_AUDIENCE
      value: oauth2-proxy-ssbno-statreg-api

  accessPolicy:
    outbound:
      external:
      - host: auth.test.ssb.no
      - host: data.qa.ssb.no

  login:
    provider: openid
    enforce:
      enabled: true
      excludePaths:
        - /docs

  gcp:
      sqlInstances:
        - type: POSTGRES_17
          # See Nais docs: https://docs.ssb.cloud.nais.io/workloads/application/reference/application-spec/#gcpsqlinstancestier
          tier: db-f1-micro # This tier MUST be increased for PROD! No SLA unless custom!
          diskAutoresize: true
          diskAutoresizeLimit: 50
          flags:
            - name: "cloudsql.enable_pgaudit"
              value: "on"
            - name: "pgaudit.log"
              value: "write"
            - name: "pgaudit.log_parameter"
              value: "on"          
          databases:
            - name: statreg-db

  prometheus:
    enabled: true
    path: /metrics
    port: "9000"
  
  liveness:
    path: /live
    port: 9000
    failureThreshold: 3
    initialDelay: 10
    periodSeconds: 30
    timeout: 5
  
  readiness:
    path: /ready
    port: 9000
    failureThreshold: 1
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  
  startup:
    path: /live
    port: 9000
    failureThreshold: 3
    initialDelay: 10
    periodSeconds: 30
    timeout: 5
status: {}
