SELECT 'AUDIT_LOG' AS table_name, COUNT(*) AS row_count, MIN(ID) AS min_id, MAX(ID) AS max_id FROM AUDIT_LOG
UNION ALL
SELECT 'FREKVENS' AS table_name, COUNT(*) AS row_count, MIN(ID) AS min_id, MAX(ID) AS max_id FROM FREKVENS
UNION ALL
SELECT 'KALENDER_DATO' AS table_name, COUNT(*) AS row_count, MIN(ID) AS min_id, MAX(ID) AS max_id FROM KALENDER_DATO
UNION ALL
SELECT 'KONTAKT' AS table_name, COUNT(*) AS row_count, MIN(ID) AS min_id, MAX(ID) AS max_id FROM KONTAKT
UNION ALL
SELECT 'KORTNAVN' AS table_name, COUNT(*) AS row_count, MIN(ID) AS min_id, MAX(ID) AS max_id FROM KORTNAVN
UNION ALL
SELECT 'PUBLISERING' AS table_name, COUNT(*) AS row_count, MIN(ID) AS min_id, MAX(ID) AS max_id FROM PUBLISERING
UNION ALL
SELECT 'REGIONALT_NIVA' AS table_name, COUNT(*) AS row_count, MIN(ID) AS min_id, MAX(ID) AS max_id FROM REGIONALT_NIVA
UNION ALL
SELECT 'SEKSJON' AS table_name, COUNT(*) AS row_count, MIN(ID) AS min_id, MAX(ID) AS max_id FROM SEKSJON
UNION ALL
SELECT 'STATISTIKK' AS table_name, COUNT(*) AS row_count, MIN(ID) AS min_id, MAX(ID) AS max_id FROM STATISTIKK
UNION ALL
SELECT 'STATISTIKK_KONTAKTER' AS table_name, COUNT(*) AS row_count, MIN(STATISTIKK_ID) AS min_id, MAX(STATISTIKK_ID) AS max_id FROM STATISTIKK_KONTAKTER
UNION ALL
SELECT 'STATISTIKK_REGIONALE_NIVAER' AS table_name, COUNT(*) AS row_count, MIN(REGIONALT_NIVA_ID) AS min_id, MAX(REGIONALT_NIVA_ID) AS max_id FROM STATISTIKK_REGIONALE_NIVAER
UNION ALL
SELECT 'VARIANT' AS table_name, COUNT(*) AS row_count, MIN(ID) AS min_id, MAX(ID) AS max_id FROM VARIANT;
