// This file is auto-generated by @hey-api/openapi-ts

export {
  postCalendarBlockedReleaseDaysByDateBody,
  type PostCalendarBlockedReleaseDaysByDateBody,
  postReleasesBulkApproveBody,
  type PostReleasesBulkApproveBody,
  postShortnamesBody,
  type PostShortnamesBody,
  postStatisticsByShortnameBody,
  type PostStatisticsByShortnameBody,
  postStatisticsByShortnameVariantsBody,
  type PostStatisticsByShortnameVariantsBody,
  postStatisticsByShortnameVariantsByIdReleasesBody,
  type PostStatisticsByShortnameVariantsByIdReleasesBody,
  putReleasesByIdBody,
  type PutReleasesByIdBody,
  putStatisticsByShortnameBody,
  type PutStatisticsByShortnameBody,
  putStatisticsByShortnameContactsBody,
  type PutStatisticsByShortnameContactsBody,
  putStatisticsByShortnameVariantsByIdBody,
  type PutStatisticsByShortnameVariantsByIdBody,
} from './zod.gen'
