// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod'

export const zError = z.object({
  message: z.string(),
})

export const zBlockedReleaseDate = z.object({
  date: z.iso.date().optional(),
  automatically_blocked: z.boolean().optional(),
  blocked_comment: z.string().optional(),
})

/**
 * Map of ISO date (YYYY-MM-DD) to day information, ie status
 */
export const zCalenderDate = z.record(z.string(), z.never())

export const zContact = z.object({
  name: z.string().readonly().optional(),
  principalName: z.string().readonly(),
})

export const zDivision = z.object({
  code: z.string().optional(),
  name: z.string().readonly().optional(),
  note: z.string().optional(),
})

export const zFrequency = z.object({
  name: z.string().optional(),
  code: z.string().optional(),
})

/**
 * Text field to specify variant beyond frequency and revision
 */
export const zLevelOfDetail = z.object({
  name: z.string().optional(),
  name_en: z.string().optional(),
})

/**
 * Valid region levels are (name in parethesis): L (Land), LD (Landsdel), F (Fylke), K (Kommune), BD (Bydel og krets)
 */
export const zRegionLevel = z.object({
  code: z.string().optional(),
  name: z.string().optional(),
})

/**
 * A shortname with its identifier
 */
export const zShortname = z.object({
  id: z.int().readonly(),
  shortname: z.string(),
})

/**
 * Shortnames with its corresponding statistic name
 */
export const zShortnameListing = z.object({
  shortname: z.string().optional(),
  statistic_name: z.string().optional(),
})

export const zRelease = z.object({
  id: z.int().readonly().optional(),
  publish_time: z.iso.datetime().optional(),
  period_to: z.iso.date().optional(),
  period_from: z.iso.date().optional(),
})

export const zReleaseCreate = zRelease.and(
  z.object({
    release_date_precision: z.string().optional(),
  })
)

export const zReleaseUpdate = zRelease.and(
  z.object({
    comment: z.string().optional(),
    release_date_precision: z.string().optional(),
  })
)

export const zReleaseGet = zRelease.and(
  z.object({
    approval_status: z.string().nullish(),
    statistic: z
      .object({
        shortname: z.string().readonly().optional(),
        name: z.string().readonly().optional(),
        name_en: z.string().readonly().optional(),
      })
      .optional(),
    measuring_period_title: z.string().readonly().optional(),
  })
)

/**
 * Valid revision codes are:	I (Ingen), B (Beregnede), E (Endelige), F (Foreløpige), R (Reviderte), IG (Integrert)
 */
export const zRevision = z.object({
  code: z.string().optional(),
})

export const zReleaseDetails = zReleaseGet.and(
  z.object({
    has_versions: z.boolean().optional(),
    variant: z
      .object({
        id: z.int().readonly().optional(),
        frequency: zFrequency.optional(),
        revision: zRevision.optional(),
      })
      .optional(),
    cancelled: z.boolean().optional(),
    release_date_precision: z.string().optional(),
  })
)

export const zReleaseListing = zReleaseGet.and(
  z.object({
    frequency: zFrequency.optional(),
    revision: zRevision.optional(),
  })
)

/**
 * Statistic status code - K (Kommende), A (Aktiv), IA (Ikke-aktiv), UT (Opphørt), SA (Sammenslått), SP (Splittet)
 */
export const zStatisticStatusInput = z.enum(['K', 'A', 'IA', 'UT', 'SA', 'SP'])

export const zStatisticDivisionInput = z.string()

export const zStatisticNameInput = z.string()

/**
 * Main language code - nn (Nynorsk), nb (Bokmål)
 */
export const zStatisticMainLanguageInput = z.enum(['nn', 'nb'])

export const zStatisticContactsInput = z.array(z.string())

/**
 * Approval status - GODKJENT (Approved), AVVIST (Rejected), FORSLAG (Proposal)
 */
export const zStatisticApprovalStatusInput = z.enum(['GODKJENT', 'AVVIST', 'FORSLAG'])

export const zStatisticFirstReleasedAtInput = z.iso.date()

export const zStatisticYearlyReportingInput = z.boolean()

export const zStatisticRegionLevelsInput = z.array(z.enum(['L', 'LD', 'F', 'K', 'BD']))

export const zStatisticPreviousTopicCodesInput = z.string()

export const zStatisticCommentInput = z.string()

export const zStatisticRelationInput = z.string()

export const zStatistic = z.object({
  shortname: z.string().readonly().optional(),
  main_language: z.string().optional(),
  status: z
    .object({
      code: z.string().optional(),
    })
    .optional(),
  name: z.string().optional(),
  name_en: z.string().optional(),
  approval_status: z.string().optional(),
})

export const zStatisticListing = zStatistic.and(
  z.object({
    division: zDivision.optional(),
    contacts: z.array(zContact).optional(),
  })
)

export const zVariant = z.object({
  id: z.int().readonly().optional(),
  version: z.int().optional(),
  updated_at: z.iso.datetime().readonly().optional(),
  level_of_detail: zLevelOfDetail.optional(),
  created_at: z.iso.datetime().readonly().optional(),
  cancelled: z.boolean().optional(),
  frequency: zFrequency.optional(),
  revision: zRevision.optional(),
})

export const zStatisticVariantsInput = z.array(zVariant)

export const zStatisticCreateUpcoming = z.object({
  status: z.literal('K'),
  division: zStatisticDivisionInput,
  name: zStatisticNameInput,
  name_en: zStatisticNameInput.optional(),
  main_language: zStatisticMainLanguageInput.optional(),
  contacts: zStatisticContactsInput.optional(),
  variants: zStatisticVariantsInput.optional(),
  approval_status: zStatisticApprovalStatusInput.optional(),
  first_released_at: zStatisticFirstReleasedAtInput.optional(),
  yearly_reporting: zStatisticYearlyReportingInput.optional(),
  statistic_region_levels: zStatisticRegionLevelsInput.optional(),
  previous_topic_codes: zStatisticPreviousTopicCodesInput.optional(),
  comment: zStatisticCommentInput.optional(),
})

export const zStatisticCreateActive = z.object({
  status: z.literal('A'),
  division: zStatisticDivisionInput,
  name: zStatisticNameInput,
  name_en: zStatisticNameInput,
  main_language: zStatisticMainLanguageInput,
  contacts: zStatisticContactsInput,
  variants: zStatisticVariantsInput,
  approval_status: zStatisticApprovalStatusInput.optional(),
  first_released_at: zStatisticFirstReleasedAtInput.optional(),
  yearly_reporting: zStatisticYearlyReportingInput.optional(),
  statistic_region_levels: zStatisticRegionLevelsInput.optional(),
  previous_topic_codes: zStatisticPreviousTopicCodesInput.optional(),
  comment: zStatisticCommentInput.optional(),
})

export const zStatisticUpdate = z.object({
  status: zStatisticStatusInput,
  division: zStatisticDivisionInput,
  name: zStatisticNameInput,
  name_en: zStatisticNameInput,
  main_language: zStatisticMainLanguageInput,
  contacts: zStatisticContactsInput.optional(),
  variants: zStatisticVariantsInput.optional(),
  approval_status: zStatisticApprovalStatusInput.optional(),
  first_released_at: zStatisticFirstReleasedAtInput,
  yearly_reporting: zStatisticYearlyReportingInput,
  statistic_region_levels: zStatisticRegionLevelsInput,
  previous_topic_codes: zStatisticPreviousTopicCodesInput,
  comment: zStatisticCommentInput,
  relation: zStatisticRelationInput,
})

export const zStatisticDetails = zStatistic.and(
  z.object({
    version: z.int().optional(),
    division: zDivision.optional(),
    first_released_at: z.iso.date().optional(),
    yearly_reporting: z.boolean().optional(),
    previous_topic_codes: z.string().optional(),
    relation: z
      .object({
        shortname: z.string().optional(),
        name: z.string().readonly().optional(),
        name_en: z.string().readonly().optional(),
      })
      .optional(),
    updated_at: z.iso.datetime().readonly().optional(),
    comment: z.string().optional(),
    created_at: z.iso.datetime().readonly().optional(),
    variants: z.array(zVariant).optional(),
    contacts: z.array(zContact).optional(),
    statistic_region_levels: z.array(zRegionLevel).optional(),
  })
)

export const zDivisionWritable = z.object({
  code: z.string().optional(),
  note: z.string().optional(),
})

/**
 * A shortname with its identifier
 */
export const zShortnameWritable = z.object({
  shortname: z.string(),
})

export const zReleaseWritable = z.object({
  publish_time: z.iso.datetime().optional(),
  period_to: z.iso.date().optional(),
  period_from: z.iso.date().optional(),
})

export const zReleaseCreateWritable = zReleaseWritable.and(
  z.object({
    release_date_precision: z.string().optional(),
  })
)

export const zReleaseUpdateWritable = zReleaseWritable.and(
  z.object({
    comment: z.string().optional(),
    release_date_precision: z.string().optional(),
  })
)

export const zReleaseGetWritable = zReleaseWritable.and(
  z.object({
    approval_status: z.string().nullish(),
  })
)

export const zReleaseDetailsWritable = zReleaseGetWritable.and(
  z.object({
    has_versions: z.boolean().optional(),
    variant: z
      .object({
        frequency: zFrequency.optional(),
        revision: zRevision.optional(),
      })
      .optional(),
    cancelled: z.boolean().optional(),
    release_date_precision: z.string().optional(),
  })
)

export const zReleaseListingWritable = zReleaseGetWritable.and(
  z.object({
    frequency: zFrequency.optional(),
    revision: zRevision.optional(),
  })
)

export const zStatisticWritable = z.object({
  main_language: z.string().optional(),
  status: z
    .object({
      code: z.string().optional(),
    })
    .optional(),
  name: z.string().optional(),
  name_en: z.string().optional(),
  approval_status: z.string().optional(),
})

export const zStatisticListingWritable = zStatisticWritable.and(
  z.object({
    division: zDivisionWritable.optional(),
    contacts: z.array(z.unknown()).optional(),
  })
)

export const zVariantWritable = z.object({
  version: z.int().optional(),
  level_of_detail: zLevelOfDetail.optional(),
  cancelled: z.boolean().optional(),
  frequency: zFrequency.optional(),
  revision: zRevision.optional(),
})

export const zStatisticVariantsInputWritable = z.array(zVariantWritable)

export const zStatisticCreateUpcomingWritable = z.object({
  status: z.literal('K'),
  division: zStatisticDivisionInput,
  name: zStatisticNameInput,
  name_en: zStatisticNameInput.optional(),
  main_language: zStatisticMainLanguageInput.optional(),
  contacts: zStatisticContactsInput.optional(),
  variants: zStatisticVariantsInputWritable.optional(),
  approval_status: zStatisticApprovalStatusInput.optional(),
  first_released_at: zStatisticFirstReleasedAtInput.optional(),
  yearly_reporting: zStatisticYearlyReportingInput.optional(),
  statistic_region_levels: zStatisticRegionLevelsInput.optional(),
  previous_topic_codes: zStatisticPreviousTopicCodesInput.optional(),
  comment: zStatisticCommentInput.optional(),
})

export const zStatisticCreateActiveWritable = z.object({
  status: z.literal('A'),
  division: zStatisticDivisionInput,
  name: zStatisticNameInput,
  name_en: zStatisticNameInput,
  main_language: zStatisticMainLanguageInput,
  contacts: zStatisticContactsInput,
  variants: zStatisticVariantsInputWritable,
  approval_status: zStatisticApprovalStatusInput.optional(),
  first_released_at: zStatisticFirstReleasedAtInput.optional(),
  yearly_reporting: zStatisticYearlyReportingInput.optional(),
  statistic_region_levels: zStatisticRegionLevelsInput.optional(),
  previous_topic_codes: zStatisticPreviousTopicCodesInput.optional(),
  comment: zStatisticCommentInput.optional(),
})

export const zStatisticUpdateWritable = z.object({
  status: zStatisticStatusInput,
  division: zStatisticDivisionInput,
  name: zStatisticNameInput,
  name_en: zStatisticNameInput,
  main_language: zStatisticMainLanguageInput,
  contacts: zStatisticContactsInput.optional(),
  variants: zStatisticVariantsInputWritable.optional(),
  approval_status: zStatisticApprovalStatusInput.optional(),
  first_released_at: zStatisticFirstReleasedAtInput,
  yearly_reporting: zStatisticYearlyReportingInput,
  statistic_region_levels: zStatisticRegionLevelsInput,
  previous_topic_codes: zStatisticPreviousTopicCodesInput,
  comment: zStatisticCommentInput,
  relation: zStatisticRelationInput,
})

export const zStatisticDetailsWritable = zStatisticWritable.and(
  z.object({
    version: z.int().optional(),
    division: zDivisionWritable.optional(),
    first_released_at: z.iso.date().optional(),
    yearly_reporting: z.boolean().optional(),
    previous_topic_codes: z.string().optional(),
    relation: z
      .object({
        shortname: z.string().optional(),
      })
      .optional(),
    comment: z.string().optional(),
    variants: z.array(zVariantWritable).optional(),
    contacts: z.array(z.unknown()).optional(),
    statistic_region_levels: z.array(zRegionLevel).optional(),
  })
)

/**
 * Number of items skipped before starting the results list
 */
export const zPaginationStart = z.int().default(0)

/**
 * Maximum number of items returned
 */
export const zPaginationCount = z.int().default(10)

/**
 * Sorting fields separated by comma. Default order is Ascending (ASC), minus(-) should be used in front of field name for Descending (DESC) order.
 */
export const zSort = z.string()

/**
 * Filter by shortname(s) separated by comma.
 */
export const zShortnameFilter = z.string()

/**
 * Filter by approval status. Valid values are "GODKJENT", "FORSLAG" and "AVVIST".
 */
export const zApprovalStatusFilter = z.string()

/**
 * Filter by contact initial(s) separated by comma.
 */
export const zContactFilter = z.string()

export const postShortnamesBody = z.object({
  shortname: z.string().max(14),
})

export type PostShortnamesBody = z.infer<typeof postShortnamesBody>

export const zGetStatisticsQuery = z.object({
  start: z.int().optional().default(0),
  count: z.int().optional().default(10),
  shortname: z.string().optional(),
  contact: z.string().optional(),
  sort: z.string().optional(),
})

export const zGetStatisticsByShortnamePath = z.object({
  shortname: z.string(),
})

export const postStatisticsByShortnameBody = z.union([zStatisticCreateUpcomingWritable, zStatisticCreateActiveWritable])

export type PostStatisticsByShortnameBody = z.infer<typeof postStatisticsByShortnameBody>

export const zPostStatisticsByShortnamePath = z.object({
  shortname: z.string(),
})

export const putStatisticsByShortnameBody = zStatisticUpdateWritable

export type PutStatisticsByShortnameBody = z.infer<typeof putStatisticsByShortnameBody>

export const zPutStatisticsByShortnamePath = z.object({
  shortname: z.string(),
})

export const postStatisticsByShortnameVariantsBody = zVariantWritable

export type PostStatisticsByShortnameVariantsBody = z.infer<typeof postStatisticsByShortnameVariantsBody>

export const putStatisticsByShortnameVariantsByIdBody = zVariantWritable

export type PutStatisticsByShortnameVariantsByIdBody = z.infer<typeof putStatisticsByShortnameVariantsByIdBody>

export const zPutStatisticsByShortnameVariantsByIdPath = z.object({
  shortname: z.string(),
  id: z.string(),
})

export const zGetStatisticsByShortnameVariantsByIdReleasesPath = z.object({
  shortname: z.string(),
  id: z.int(),
})

export const zGetStatisticsByShortnameVariantsByIdReleasesQuery = z.object({
  start: z.int().optional().default(0),
  count: z.int().optional().default(10),
})

export const postStatisticsByShortnameVariantsByIdReleasesBody = zReleaseCreateWritable

export type PostStatisticsByShortnameVariantsByIdReleasesBody = z.infer<
  typeof postStatisticsByShortnameVariantsByIdReleasesBody
>

export const zPostStatisticsByShortnameVariantsByIdReleasesPath = z.object({
  shortname: z.string(),
  id: z.int(),
})

export const putStatisticsByShortnameContactsBody = z.object({
  principalNames: z.array(z.string()),
})

export type PutStatisticsByShortnameContactsBody = z.infer<typeof putStatisticsByShortnameContactsBody>

export const zPutStatisticsByShortnameContactsPath = z.object({
  shortname: z.string(),
})

export const zGetReleasesQuery = z.object({
  start: z.int().optional().default(0),
  count: z.int().optional().default(10),
  sort: z.string().optional(),
  shortname: z.string().optional(),
  approval_status: z.string().optional(),
  publish_time_after: z.iso.datetime().optional(),
  publish_time_before: z.iso.datetime().optional(),
})

export const postReleasesBulkApproveBody = z.object({
  ids: z.array(z.int()),
})

export type PostReleasesBulkApproveBody = z.infer<typeof postReleasesBulkApproveBody>

export const zGetReleasesByIdPath = z.object({
  id: z.string(),
})

export const putReleasesByIdBody = zReleaseUpdateWritable

export type PutReleasesByIdBody = z.infer<typeof putReleasesByIdBody>

export const zPutReleasesByIdPath = z.object({
  id: z.string(),
})

export const zGetReleasesByIdVersionsPath = z.object({
  id: z.string(),
})

export const zGetCalendarQuery = z.object({
  fromDate: z.iso.date().optional(),
  toDate: z.iso.date().optional(),
})

export const zDeleteCalendarBlockedReleaseDaysByDatePath = z.object({
  date: z.iso.date(),
})

export const postCalendarBlockedReleaseDaysByDateBody = z.object({
  blocked_comment: z.string().optional(),
})

export type PostCalendarBlockedReleaseDaysByDateBody = z.infer<typeof postCalendarBlockedReleaseDaysByDateBody>

export const zPostCalendarBlockedReleaseDaysByDatePath = z.object({
  date: z.iso.date(),
})
