/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/statistics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List of all statistics */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of statistics */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Statistic_listing'][]
          }
        }
      }
    }
    put?: never
    /** Create a new statistic */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Statistic_details']
        }
      }
      responses: {
        /** @description Statistic details */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Statistic_details']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/statistics/{shortname}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a statistic by its shortname */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          shortname: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Statistic details with all its variants */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Statistic_details']
          }
        }
      }
    }
    /** Update a statistic */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          shortname: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Statistic_details']
        }
      }
      responses: {
        /** @description Updated statistic details with all its variants */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Statistic_details']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/statistics/{shortname}/variants': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a variant on a spesific statistic */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Variant']
        }
      }
      responses: {
        /** @description The created variant */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Variant']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/statistics/{shortname}/variants/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update a variant */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          shortname: string
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Variant']
        }
      }
      responses: {
        /** @description Updated variant details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Variant']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/statistics/{shortname}/versions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all versions with changes and comment. Response object TBD */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of versions. Response object TBD */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/releases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all releases. TBD; Pagination and filtering in backend or frontend */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of releases */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Release_listing'][]
          }
        }
      }
    }
    put?: never
    /** Create a new release */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Release_details']
        }
      }
      responses: {
        /** @description Release details */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Release_details']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/releases/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get release by id */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Release details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Release_details']
          }
        }
      }
    }
    /** Update a release */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Release_details']
        }
      }
      responses: {
        /** @description Updated release details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Release_details']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/releases/{id}/versions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all versions on a release with change and comment. Response object TBD */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of versions. Response object TBD */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/frequencies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all frequencies */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of frequencies */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Frequency'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/calendar': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all days within date range with releases, statuses, nonreleaseing days and reasons using defult parameters */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of days */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Calender_date'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/calendar/{fromdate}-{todate}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all days within date range with releases, statuses, nonreleaseing days and reasons */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          fromdate: string
          todate: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of days in range */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Calender_date'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/calendar/blocked-release-days': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List with all manually added blocked days */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List with blocked days */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Blocked_release_date'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/calendar/blocked-release-days/{date}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Manually block a day */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          date: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            blocked_comment?: string
          }
        }
      }
      responses: {
        /** @description Updated list with blocked days */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Blocked_release_date'][]
          }
        }
      }
    }
    /** Delete a manually blocked day */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          date: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Updated list */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Blocked_release_date'][]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Blocked_release_date: {
      /** Format: date-time */
      date?: string
      blocked_comment?: string
    }
    Calender_date: {
      /** Format: date-time */
      date?: string
      readonly is_blocked?: boolean
      readonly blocked_comment?: string | null
      releases?: {
        readonly release_id?: number
        readonly statistic_shortname?: string
        readonly statistic_name?: components['schemas']['Translations']
      }[]
    }
    Contact: {
      readonly name?: string
      readonly username?: string
      /** Format: mobile */
      readonly mobile?: string
      /** Format: email */
      readonly email?: string
    }
    Frequency: {
      readonly id?: number
      name?: components['schemas']['Translations']
      code?: string
    }
    Release_details: {
      readonly id?: number
      version?: number
      /** Format: date-time */
      publish_time?: string
      has_versions?: boolean
      /** Format: date-time */
      readonly updated_at?: string
      comment?: string
      approval_status?: string | null
      variant_id?: number
      /** Format: date-time */
      period_to?: string
      /** Format: date-time */
      period_from?: string
      cancelled?: boolean
      /** Format: date-time */
      readonly created_at?: string
      release_date_precision?: string
      import_flag?: boolean | null
    }
    Release_listing: {
      readonly id?: number
      /** Format: date-time */
      publish_time?: string
      approval_status?: string | null
      /** Format: date-time */
      period_to?: string
      /** Format: date-time */
      period_from?: string
      statistic?: {
        readonly shortname?: string
        readonly name?: components['schemas']['Translations']
      }
      frequency?: {
        readonly name?: components['schemas']['Translations']
      }
    }
    Statistic_details: {
      version?: number
      readonly shortname?: string
      approval_status?: string | null
      main_language?: string
      division?: {
        code?: string | null
        readonly name?: components['schemas']['Translations']
      }
      /** Format: date */
      first_released_at?: string | null
      yearly_reporting?: boolean
      status?: {
        code?: string
      }
      previous_topic_codes?: string | null
      relation?: {
        shortname?: string
        readonly name?: components['schemas']['Translations']
      }
      name?: components['schemas']['Translations']
      /** Format: date-time */
      readonly updated_at?: string
      comment?: string
      /** Format: date-time */
      readonly created_at?: string
      variants?: components['schemas']['Variant'][]
      contacts?: {
        username?: string
        email?: string
        name?: string
      }[]
      statistic_region_levels?: components['schemas']['Translations'][]
    }
    Statistic_listing: {
      readonly shortname?: string
      main_language?: string
      status?: {
        code?: string
      }
      name?: components['schemas']['Translations']
      contacts?: {
        username?: string | null
        email?: string
      }[]
    }
    Translations: {
      language_code?: string
      text?: string
    }[]
    Variant: {
      readonly id?: number
      version?: number
      /** Format: date-time */
      readonly updated_at?: string
      level_of_detail?: {
        name?: components['schemas']['Translations']
      }
      /** Format: date-time */
      readonly created_at?: string
      cancelled?: boolean
      freqency?: {
        readonly name?: components['schemas']['Translations']
      }
      revision?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
