/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/publisering/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List publications (UI)
         * @description Renders the HTML list view with optional filters and sorting. Mirrors `PubliseringController.list`.
         */
        get: operations["publiseringListView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisering/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Open create-publication form (UI)
         * @description Renders the HTML form to create a publication. Mirrors `PubliseringController.create`.
         */
        get: operations["publiseringCreateForm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisering/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a publication (UI action)
         * @description Deletes a publication and redirects. Mirrors `PubliseringController.delete` (POST).
         */
        post: operations["publiseringDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisering/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Open edit-publication form (UI)
         * @description Renders the HTML form to edit an existing publication. Mirrors `PubliseringController.edit`.
         */
        get: operations["publiseringEditForm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisering/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update a publication (UI action)
         * @description Updates a publication and redirects. Mirrors `PubliseringController.update` (POST).
         */
        post: operations["publiseringUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisering/versjoner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show audit versions for a publication (UI)
         * @description Renders an HTML page grouping audit entries by version. Mirrors `PubliseringController.versjoner`.
         */
        get: operations["publiseringVersionsView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisering/flytt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Move publication to another variant (UI)
         * @description Shows a UI to move a publication to a different variant. Mirrors `PubliseringController.flytt`.
         */
        get: operations["publiseringFlyttForm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisering/lagreVariant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the variant of a publication (UI action)
         * @description Assigns a different Variant to the publication and redirects. Mirrors `PubliseringController.lagreVariant` (POST).
         */
        post: operations["publiseringSaveVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisering/hentHelligdagerSperredeOgPubliseringer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get holidays and publication-day summaries
         * @description Returns holidays and per-day summaries of proposed/approved publication counts for one or more months.
         */
        get: operations["getHolidaysBlockedAndPublications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisering/avvisDesk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a publication in Desk (UI action, placeholder)
         * @description Mirrors `PubliseringController.avvisDesk`. Rejects a publication with an internal comment and redirects.
         */
        post: operations["publiseringAvvisDesk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisering/godkjennDesk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a publication in Desk (UI action, placeholder)
         * @description Mirrors `PubliseringController.godkjennDesk`. Approves a publication and redirects.
         */
        post: operations["publiseringGodkjennDesk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publisering/listDesk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List publications awaiting Desk (UI view, placeholder)
         * @description Mirrors `PubliseringController.listDesk`. Shows publications with `deskFlyt=FORSLAG`, not canceled.
         */
        get: operations["publiseringListDesk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    publiseringListView: {
        parameters: {
            query?: {
                max?: number;
                offset?: number;
                /** @description Field to sort by (default `tidspunkt`). When `statistikknavn`, sorting happens via nested association. */
                sort?: "tidspunkt" | "statistikknavn" | "dateCreated" | "id";
                order?: "asc" | "desc";
                /** @description Filter by owner section code (e.g. "350") */
                "filter.seksjon"?: string;
                /** @description Filter by `kortnavn` (LIKE) */
                "filter.kortnavn"?: string;
                /** @description Filter by contact initials (LIKE) */
                "filter.initialer"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML list view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
        };
    };
    publiseringCreateForm: {
        parameters: {
            query?: {
                /** @description Statistikk ID the new publication belongs to (`params.statistikk.id`) */
                statistikkId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML form */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Redirect (statistic not approved) */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publiseringDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Publisering ID to delete (`params.id`) */
                    id: number;
                    /** @description Optional Statistikk ID for redirect (`params.statistikk`) */
                    statistikk?: number;
                };
            };
        };
        responses: {
            /** @description Redirect when not found or delete fails */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description See Other — redirect after delete */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publiseringEditForm: {
        parameters: {
            query: {
                /** @description Publisering ID to edit (`params.id`) */
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML form */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Redirect (not found or not approved) */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publiseringUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Publisering ID (`params.id`) */
                    id: number;
                    /** @description Optimistic locking version (`params.version`) */
                    version?: number;
                    /** @description New publish timestamp (`params.tidspunkt`) */
                    tidspunkt?: string;
                    /** @description Internal comment */
                    internKommentar?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description HTML edit view re-rendered with validation errors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Redirect when not found */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description See Other — redirect after successful update */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publiseringVersionsView: {
        parameters: {
            query: {
                /** @description Publisering ID (`params.id`) */
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML versions view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Redirect when not found */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publiseringFlyttForm: {
        parameters: {
            query: {
                /** @description Publisering ID to move (`params.id`) */
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML view with variant list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Redirect (not found) */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publiseringSaveVariant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Publisering ID (`params.id`) */
                    id: number;
                    /** @description Optimistic locking version (`params.version`) */
                    version?: number;
                    /** @description Variant ID to assign (`params.variant`) */
                    variant: number;
                };
            };
        };
        responses: {
            /** @description HTML flytt view re-rendered with errors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Redirect when not found */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description See Other — redirect after success */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHolidaysBlockedAndPublications: {
        parameters: {
            query?: {
                /** @description Month (1–12) */
                mnd?: number;
                /** @description Year (e.g. 2025) */
                ar?: number;
                /** @description Number of months to include starting from (mnd, ar). If omitted, returns only (mnd, ar). */
                antallMnd?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description List of holiday date strings (format decided by server) */
                        helligdager?: string[];
                        /** @description List of tuples [dateString, level] where level describes load (e.g. "maks") */
                        publiseringsTidspunktSummer?: (string)[][];
                    };
                };
            };
        };
    };
    publiseringAvvisDesk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Publisering ID (`params.id`) */
                    id: number;
                    /** @description Internal comment explaining the rejection (`params.internKommentar`) */
                    internKommentar: string;
                };
            };
        };
        responses: {
            /** @description Re-rendered page with validation errors (e.g., missing comment) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description See Other — redirect after action */
            303: {
                headers: {
                    /** @description Redirect target (typically `/publisering/list`) */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publiseringGodkjennDesk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Publisering ID (`params.id`) */
                    id: number;
                };
            };
        };
        responses: {
            /** @description See Other — redirect after action */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    publiseringListDesk: {
        parameters: {
            query?: {
                max?: number;
                offset?: number;
                sort?: "tidspunkt" | "statistikknavn" | "dateCreated" | "id";
                order?: "asc" | "desc";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML list view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
