/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all statistics (JSON)
         * @description Returns all active statistics and their non-discontinued variants.
         */
        get: operations["listStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StatisticsResponse: {
            statistics?: components["schemas"]["StatisticItem"][];
        };
        StatisticItem: {
            id?: number;
            shortName?: string;
            name?: string;
            nameEN?: string;
            /** @description lastUpdated as string */
            modifiedTime?: string;
            /** @enum {string} */
            status?: "A" | "IA" | "UT" | "SA";
            /** @description Only non-discontinued variants (!erOpphort) */
            variants?: components["schemas"]["VariantItem"][];
        };
        VariantItem: {
            id?: number;
            /** @description Human-readable frequency (e.g., "År", "Måned") */
            frekvens?: string;
            /** @description Timestamp of previous release, or empty string */
            previousRelease?: string;
            /** @description Period start of previous release, or empty string */
            previousFrom?: string;
            /** @description Period end of previous release, or empty string */
            previousTo?: string;
            /** @description Timestamp of next release, or empty string */
            nextRelease?: string;
            /** @description Next release ID or empty string */
            nextReleaseId?: number | string;
            /** @description From getUpcomingReleases(...). Empty array if none. */
            upcomingReleases?: components["schemas"]["UpcomingRelease"][];
        };
        /** @description Exact shape from getUpcomingReleases(...) */
        UpcomingRelease: {
            id?: number;
            /** @description release.tidspunkt.toString() */
            publishTime?: string;
            /** @description release.periodeFra.toString() */
            periodFrom?: string;
            /** @description release.periodeTil.toString() */
            periodTo?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatisticsResponse"];
                };
            };
        };
    };
}
