/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/statistikk/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List statistics (UI)
         * @description Renders the HTML list view of all statistics with optional filters, pagination, and sorting.
         *     Mirrors `StatistikkController.list`.
         *     This is the UI counterpart to `/statistics`, which provides the same data in JSON form.
         */
        get: operations["statistikkListView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Create statistikk (UI form)
         * @description Renders the HTML create form. Mirrors `StatistikkController.create`.
         */
        get: operations["statistikkCreateView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete statistikk (UI action placeholder)
         * @description Currently does not delete; sets a flash message and redirects to list. Mirrors `StatistikkController.delete` (POST).
         */
        post: operations["statistikkDelete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Edit statistikk (UI form)
         * @description Renders the HTML edit view for a given statistikk. Mirrors `StatistikkController.edit`.
         */
        get: operations["statistikkEditView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update statistikk (UI action)
         * @description Updates a statistikk and redirects. Mirrors `StatistikkController.update` (POST).
         */
        post: operations["statistikkUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/versjoner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show audit versions for a statistikk (UI)
         * @description Renders an HTML page with grouped audit entries. Mirrors `StatistikkController.versjoner`.
         */
        get: operations["statistikkVersionsView"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/avvisDesk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a statistikk in Desk (UI action, placeholder)
         * @description Mirrors `StatistikkController.avvisDesk`. Rejects with internal comment and redirects.
         */
        post: operations["statistikkAvvisDesk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/godkjennDesk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a statistikk in Desk (UI action, placeholder)
         * @description Mirrors `StatistikkController.godkjennDesk`. Approves and redirects.
         */
        post: operations["statistikkGodkjennDesk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/lagreVarianter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save one or more variants (UI action, placeholder)
         * @description Placeholder for `StatistikkController.lagreVarianter`. Intended to save or update multiple `Variant` records associated with a `Statistikk`. Exact payload TBD.
         */
        post: operations["statistikkSaveVariants"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/oppdaterVarianter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update variants helper (non-routable in current code, placeholder)
         * @description Listed in inventory but the current controller declares `oppdaterVarianter` as a helper closure that takes parameters `(params, variantInstanceList)` and is not exposed as an action. If later exposed via a proper action, replace this placeholder with the actual contract.
         */
        post: operations["statistikkOppdaterVarianter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show statistikk (UI view, placeholder)
         * @description Mirrors `StatistikkController.show`. Displays a statistikk page.
         */
        get: operations["statistikkShow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/slettVariant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a variant from a statistikk (UI action)
         * @description Deletes a Variant and redirects. Mirrors `StatistikkController.slettVariant` (POST).
         */
        post: operations["statistikkDeleteVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistikk/hentKortnavn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve the list of kortnavn
         * @description Returns a list of shortnames for all statistics (used in UI selectors and XML fetchers).
         */
        get: operations["getKortnavn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    statistikkListView: {
        parameters: {
            query?: {
                max?: number;
                offset?: number;
                /** @description Field to sort by (default `statistikknavn`). When `kortnavn`, sorting happens on the nested `Kortnavn` association. */
                sort?: "statistikknavn" | "kortnavn" | "dateCreated" | "id";
                order?: "asc" | "desc";
                /** @description Filter by owner section code (e.g. "350") */
                "filter.seksjon"?: string;
                /** @description Filter by short name (`Kortnavn.navn`, LIKE) */
                "filter.kortnavn"?: string;
                /** @description Filter by contact initials (LIKE) */
                "filter.initialer"?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML list view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    statistikkCreateView: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML create view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
        };
    };
    statistikkDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": Record<string, never>;
            };
        };
        responses: {
            /** @description See Other — redirect to list */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    statistikkEditView: {
        parameters: {
            query: {
                /** @description Statistikk ID (`params.id`) */
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML edit view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Redirect when not found */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    statistikkUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Statistikk ID */
                    id: number;
                    /** @description Optimistic locking version */
                    version?: number;
                    /** @description Section ID */
                    eierseksjon?: string;
                    "kortnavn.navn"?: string;
                    "statistikk.internKommentar"?: string;
                    "statistikk.forstegangspublisering"?: string;
                    "statistikk.kontakter"?: string[];
                } & {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description HTML edit view re-rendered with validation errors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Redirect when not found */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description See Other — redirect after success */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    statistikkVersionsView: {
        parameters: {
            query: {
                /** @description Statistikk ID (`params.id`) */
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML versions view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": unknown;
                };
            };
            /** @description Redirect when not found */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    statistikkAvvisDesk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Statistikk ID (`params.id`) */
                    id: number;
                    /** @description Internal comment explaining the rejection (`params.internKommentar`) */
                    internKommentar: string;
                };
            };
        };
        responses: {
            /** @description Re-rendered page with validation errors (e.g., missing comment) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description See Other — redirect after action */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    statistikkGodkjennDesk: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Statistikk ID (`params.id`) */
                    id: number;
                };
            };
        };
        responses: {
            /** @description See Other — redirect after action */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    statistikkSaveVariants: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Re-rendered form with validation errors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Redirect after saving (typical Grails flow) */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    statistikkOppdaterVarianter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Placeholder response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    statistikkShow: {
        parameters: {
            query: {
                /** @description Statistikk ID (`params.id`) */
                id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description HTML detail view */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Redirect when not found */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    statistikkDeleteVariant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @description Variant ID to delete (`params.variant.id`) */
                    "variant.id": number;
                };
            };
        };
        responses: {
            /** @description Redirect on not found or data integrity violation */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description See Other — redirect to `/statistikk/show/{statistikkId}` */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getKortnavn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of kortnavn */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        kortnavn?: string[];
                    };
                };
            };
        };
    };
}
