\set ON_ERROR_STOP on

-- Start clean
DROP SCHEMA IF EXISTS statreg_data CASCADE;
CREATE SCHEMA statreg_data AUTHORIZATION cob;
SET search_path TO statreg_data;

-- Optional but helpful for Prisma/read-only users
GRANT USAGE ON SCHEMA statreg_data TO cob;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA statreg_data TO cob;
ALTER DEFAULT PRIVILEGES IN SCHEMA statreg_data
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO cob;

-- === BASE TABLES (no FKs yet) ===

CREATE TABLE audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  property_name VARCHAR(255),
  last_updated TIMESTAMP,
  old_value VARCHAR(255),
  actor VARCHAR(255),
  uri VARCHAR(255),
  new_value VARCHAR(255),
  persisted_object_version NUMERIC(19,0),
  date_created TIMESTAMP,
  class_name VARCHAR(255),
  event_name VARCHAR(255),
  persisted_object_id NUMERIC(19,0)
);

CREATE TABLE frekvens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version NUMERIC(19,0),
  navn VARCHAR(50),
  kode VARCHAR(50)
);

CREATE TABLE kalender_dato (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version NUMERIC(19,0),
  kommentar VARCHAR(255),
  dag TIMESTAMP
);

CREATE TABLE kontakt (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version NUMERIC(19,0),
  initialer VARCHAR(3),
  mobil VARCHAR(30),
  navn VARCHAR(130),
  last_updated TIMESTAMP,
  telefon VARCHAR(30),
  epost VARCHAR(100),
  date_created TIMESTAMP,
  inaktiv NUMERIC(1,0),
  navn_en VARCHAR(130)
);

CREATE TABLE kortnavn (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version NUMERIC(19,0),
  navn VARCHAR(20),
  last_updated TIMESTAMP,
  date_created TIMESTAMP
);

CREATE TABLE regionalt_niva (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version NUMERIC(19,0),
  navn VARCHAR(40),
  kode VARCHAR(50)
);

CREATE TABLE seksjon (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version NUMERIC(19,0),
  navn VARCHAR(100),
  kode VARCHAR(3),
  navn_en VARCHAR(100)
);

-- === TABLES WITH DEPENDENCIES ===

CREATE TABLE statistikk (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version NUMERIC(19,0),
  kortnavn_id BIGINT,
  dir_flyt VARCHAR(255),
  triggerord VARCHAR(500),
  prioritet NUMERIC(1,0),
  desk_flyt VARCHAR(255),
  sprak VARCHAR(255),
  triggerord_en VARCHAR(500),
  eierseksjon_id BIGINT,
  forstegangspublisering TIMESTAMP,
  arsrapportering NUMERIC(1,0),
  status VARCHAR(255),
  gamle_emnekoder VARCHAR(255),
  relasjon_id BIGINT, -- left as plain column; add FK if you truly relate to something
  statistikknavn VARCHAR(140),
  last_updated TIMESTAMP,
  intern_kommentar VARCHAR(255),
  statistikknavn_en VARCHAR(140),
  date_created TIMESTAMP
);

CREATE TABLE variant (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version NUMERIC(19,0),
  frekvens_id BIGINT,
  last_updated TIMESTAMP,
  revisjon VARCHAR(255),
  statistikk_id BIGINT,
  detaljniva_en VARCHAR(255),
  detaljniva VARCHAR(255),
  er_opphort NUMERIC(1,0),
  date_created TIMESTAMP
);

CREATE TABLE publisering (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version NUMERIC(19,0),
  tidspunkt TIMESTAMP,
  er_endret NUMERIC(1,0),
  last_updated TIMESTAMP,
  intern_kommentar VARCHAR(255),
  periode_til TIMESTAMP,
  desk_flyt VARCHAR(255),
  variant_id BIGINT,
  periode_fra TIMESTAMP,
  er_avlyst NUMERIC(1,0),
  date_created TIMESTAMP,
  datotype VARCHAR(255),
  import_flag NUMERIC(1,0)
);

CREATE TABLE statistikk_kontakter (
  statistikk_id BIGINT,
  kontakt_id BIGINT,
  kontakter_idx NUMERIC(10,0),
  PRIMARY KEY (statistikk_id, kontakt_id)
);

CREATE TABLE statistikk_regionale_nivaer (
  regionalt_niva_id BIGINT,
  statistikk_id BIGINT,
  PRIMARY KEY (statistikk_id, regionalt_niva_id)
);

-- === FOREIGN KEYS (so Prisma generates relations) ===

ALTER TABLE statistikk
  ADD CONSTRAINT fk_statistikk_kortnavn
    FOREIGN KEY (kortnavn_id) REFERENCES kortnavn (id),
  ADD CONSTRAINT fk_statistikk_eierseksjon
    FOREIGN KEY (eierseksjon_id) REFERENCES seksjon (id);

ALTER TABLE variant
  ADD CONSTRAINT fk_variant_frekvens
    FOREIGN KEY (frekvens_id) REFERENCES frekvens (id),
  ADD CONSTRAINT fk_variant_statistikk
    FOREIGN KEY (statistikk_id) REFERENCES statistikk (id);

ALTER TABLE publisering
  ADD CONSTRAINT fk_publisering_variant
    FOREIGN KEY (variant_id) REFERENCES variant (id);

ALTER TABLE statistikk_kontakter
  ADD CONSTRAINT fk_sk_statistikk
    FOREIGN KEY (statistikk_id) REFERENCES statistikk (id),
  ADD CONSTRAINT fk_sk_kontakt
    FOREIGN KEY (kontakt_id) REFERENCES kontakt (id);

ALTER TABLE statistikk_regionale_nivaer
  ADD CONSTRAINT fk_srn_regionalt_niva
    FOREIGN KEY (regionalt_niva_id) REFERENCES regionalt_niva (id),
  ADD CONSTRAINT fk_srn_statistikk
    FOREIGN KEY (statistikk_id) REFERENCES statistikk (id);

-- Helpful indexes on FK columns (Prisma doesn't require them but your app will thank you)
CREATE INDEX idx_statistikk_kortnavn_id ON statistikk (kortnavn_id);
CREATE INDEX idx_statistikk_eierseksjon_id ON statistikk (eierseksjon_id);
CREATE INDEX idx_variant_frekvens_id ON variant (frekvens_id);
CREATE INDEX idx_variant_statistikk_id ON variant (statistikk_id);
CREATE INDEX idx_publisering_variant_id ON publisering (variant_id);
CREATE INDEX idx_sk_statistikk_id ON statistikk_kontakter (statistikk_id);
CREATE INDEX idx_sk_kontakt_id ON statistikk_kontakter (kontakt_id);
CREATE INDEX idx_srn_regionalt_niva_id ON statistikk_regionale_nivaer (regionalt_niva_id);
CREATE INDEX idx_srn_statistikk_id ON statistikk_regionale_nivaer (statistikk_id);
