/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/statistics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List of all statistics */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of statistics */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Statistic_listing'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/statistics/{shortname}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a statistic by its shortname */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          shortname: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Statistic details with all its variants */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Statistic_details']
          }
        }
      }
    }
    /** Update a statistic */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          shortname: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Statistic_update']
        }
      }
      responses: {
        /** @description Updated statistic details with all its variants */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Statistic_details']
          }
        }
      }
    }
    /** Create a new statistic */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Statistic_create']
        }
      }
      responses: {
        /** @description Statistic details */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Statistic_details']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/statistics/{shortname}/releases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all releases for a statistic */
    get: {
      parameters: {
        query?: {
          start?: number
          count?: number
        }
        header?: never
        path: {
          shortname: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of releases */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              total?: number
              releases?: components['schemas']['Release_listing'][]
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/statistics/{shortname}/variants': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create a variant on a spesific statistic */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Variant']
        }
      }
      responses: {
        /** @description The created variant */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Variant']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/statistics/{shortname}/variants/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update a variant */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          shortname: string
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Variant']
        }
      }
      responses: {
        /** @description Updated variant details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Variant']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/statistics/{shortname}/variants/{id}/releases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all releases for one variant */
    get: {
      parameters: {
        query?: {
          start?: number
          count?: number
        }
        header?: never
        path: {
          shortname: string
          id: number
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of releases based on variant */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              total?: number
              releases?: components['schemas']['Release_listing'][]
            }
          }
        }
      }
    }
    put?: never
    /** Create a new release */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Release_create']
        }
      }
      responses: {
        /** @description Release details */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Release_details']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/statistics/{shortname}/versions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all versions with changes and comment. Response object TBD */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of versions. Response object TBD */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/releases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all releases. TBD; Pagination and filtering in backend or frontend */
    get: {
      parameters: {
        query?: {
          start?: number
          count?: number
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of releases */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              total?: number
              releases?: components['schemas']['Release_listing'][]
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/releases/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get release by id */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Release details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Release_details']
          }
        }
      }
    }
    /** Update a release */
    put: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['Release_update']
        }
      }
      responses: {
        /** @description Updated release details */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Release_details']
          }
        }
      }
    }
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/releases/{id}/versions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all versions on a release with change and comment. Response object TBD */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of versions. Response object TBD */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/frequencies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all frequencies */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List of frequencies */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Frequency'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/calendar': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get status for all days in a period */
    get: {
      parameters: {
        query?: {
          fromDate?: string
          toDate?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Object with days in range and their status */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Calender_date']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/calendar/blocked-release-days': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List with all manually added blocked days */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description List with blocked days */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Blocked_release_date'][]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/calendar/blocked-release-days/{date}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Manually block a day */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          date: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            blocked_comment?: string
          }
        }
      }
      responses: {
        /** @description Updated list with blocked days */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Blocked_release_date'][]
          }
        }
      }
    }
    /** Delete a manually blocked day */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          date: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Updated list */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['Blocked_release_date'][]
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Blocked_release_date: {
      /** Format: date-time */
      date?: string
      blocked_comment?: string
    }
    /**
     * @description Map of ISO date (YYYY-MM-DD) to day information, ie status
     * @example {
     *       "2026-05-03": {
     *         "status": "blocked"
     *       },
     *       "2026-05-04": {
     *         "status": "none"
     *       },
     *       "2026-05-05": {
     *         "status": "few"
     *       }
     *     }
     */
    Calender_date: {
      [key: string]: {
        /** @description Can be one of "blocked", "none", "few", "many", "full" */
        status: string
      }
    }
    Contact: {
      readonly name?: string
      readonly username?: string
      /** Format: mobile */
      readonly mobile?: string
      /** Format: email */
      readonly email?: string
    }
    Frequency: {
      name?: string
      code?: string
    }
    /** @description Text field to specify variant beyond frequency and revision */
    Level_of_detail: {
      name?: string | null
      name_en?: string | null
    }
    /** @description Valid region levels are (name in parethesis): L (Land), LD (Landsdel), F (Fylke), K (Kommune), BD (Bydel og krets) */
    Region_level: {
      code?: string
      name?: string
    }
    Release: {
      readonly id?: number
      /** Format: date-time */
      publish_time?: string
      /** Format: date-time */
      period_to?: string
      /** Format: date-time */
      period_from?: string
    }
    Release_create: components['schemas']['Release'] & {
      release_date_precision?: string
    }
    Release_update: components['schemas']['Release'] & {
      comment?: string
      release_date_precision?: string
    }
    Release_get: components['schemas']['Release'] & {
      approval_status?: string | null
      statistic?: {
        readonly shortname?: string
        readonly name?: string
        readonly name_en?: string
      }
    }
    Release_details: components['schemas']['Release_get'] & {
      has_versions?: boolean
      variant?: {
        readonly id?: number
        frequency?: components['schemas']['Frequency']
        revision?: components['schemas']['Revision']
      }
      cancelled?: boolean
      release_date_precision?: string
    }
    Release_listing: components['schemas']['Release_get'] & {
      frequency?: components['schemas']['Frequency']
    }
    /** @description Valid revision codes are:	I (Ingen), B (Beregnede), E (Endelige), F (Foreløpige), R (Reviderte), IG (Integrert) */
    Revision: {
      name?: string
      code?: string
    }
    Statistic: {
      readonly shortname?: string
      /** @description Main language will be either 'nn' or 'nb' for statistics */
      main_language?: string
      status?: {
        code?: string
      }
      name?: string
      name_en?: string
      /** @description Is one of 'GODKJENT', 'AVVIST' or 'FORSLAG' */
      approval_status?: string
    }
    Statistic_create: {
      division?: string | null
      /** Format: date */
      first_released_at?: string | null
      yearly_reporting?: boolean
      statistic_region_levels?: components['schemas']['Region_level'][]
      previous_topic_codes?: string | null
      comment?: string
    } & components['schemas']['Statistic']
    Statistic_update: {
      relation?: string | null
    } & components['schemas']['Statistic_create']
    Statistic_details: {
      version?: number
      division?: {
        code?: string | null
        readonly name?: string
      }
      /** Format: date */
      first_released_at?: string | null
      yearly_reporting?: boolean
      previous_topic_codes?: string | null
      relation?: {
        shortname?: string
        readonly name?: string
        readonly name_en?: string
      }
      /** Format: date-time */
      readonly updated_at?: string
      comment?: string
      /** Format: date-time */
      readonly created_at?: string
      variants?: components['schemas']['Variant'][]
      contacts?: {
        username?: string | null
        email?: string
        name?: string
      }[]
      statistic_region_levels?: components['schemas']['Region_level'][]
    } & components['schemas']['Statistic']
    Statistic_listing: {
      contacts?: {
        username?: string | null
        email?: string
      }[]
    } & components['schemas']['Statistic']
    Variant: {
      readonly id?: number
      version?: number
      /** Format: date-time */
      readonly updated_at?: string
      level_of_detail?: components['schemas']['Level_of_detail']
      /** Format: date-time */
      readonly created_at?: string
      cancelled?: boolean
      frequency?: components['schemas']['Frequency']
      revision?: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
