name: Build and test
on:
  pull_request:
    branches: ["develop", "main"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # placeholder URL, needed to generate client and build application
      PGURL: postgresql://user@localhost:5432/statreg_db
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run generate
      - run: npm run build --if-present
      - run: npm run ci-test
      - run: npm run lint
      - run: npm run generate:api-types

      - name: Check match between generated api types and openapi spec
        # If api-types.d.ts has uncommited changes after the previous step (generate api-types)
        # that means that there is a mismatch between api-types and openapi spec
        run: |
          if ! git diff --exit-code ./backend/src/types/api-types.d.ts; then
            echo "❌ There's a mismatch between generated api types and openapi spec. Please run 'npm run generate:api-types' to update types, or revert changes to the spec."
            exit 1
          fi

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run integration tests
        run: docker compose -f docker-compose-test.yaml up --abort-on-container-exit --exit-code-from tests
