name: Build and test
on:
  pull_request:
    branches: ["develop", "main"]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # placeholder URL, needed to generate client and build application
      PGURL: postgresql://user@localhost:5432/statreg_db
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run generate
      - run: npm run build --if-present
      - run: npm run ci-test
      - run: npm run lint
